CREATE TABLE IF NOT EXISTS readers
(
    Id SERIAL PRIMARY KEY,
    CardNumber CHARACTER VARYING(30),
    FullName CHARACTER VARYING(30),
    Adress CHARACTER VARYING(30),
    Age INTEGER
);
CREATE TABLE IF NOT EXISTS books
(
    Id SERIAL PRIMARY KEY,
    Title CHARACTER VARYING(30),
    Chipher CHARACTER VARYING(30),
    YearOfPublic CHARACTER VARYING(30),
    NumberOfPages INTEGER,
    Price CHARACTER VARYING(30),
    NumberOfCopy INTEGER,
    Id_publisher INTEGER REFERENCES Customers (Id),
);
CREATE TABLE IF NOT EXISTS readers
(
    Id SERIAL PRIMARY KEY,
    CardNumber CHARACTER VARYING(30),
    FullName CHARACTER VARYING(30),
    Adress CHARACTER VARYING(30),
    Age INTEGER
);
CREATE TABLE IF NOT EXISTS readers
(
    Id SERIAL PRIMARY KEY,
    CardNumber CHARACTER VARYING(30),
    FullName CHARACTER VARYING(30),
    Adress CHARACTER VARYING(30),
    Age INTEGER
);
CREATE TABLE IF NOT EXISTS readers
(
    Id SERIAL PRIMARY KEY,
    CardNumber CHARACTER VARYING(30),
    FullName CHARACTER VARYING(30),
    Adress CHARACTER VARYING(30),
    Age INTEGER
);
CREATE TABLE IF NOT EXISTS readers
(
    Id SERIAL PRIMARY KEY,
    CardNumber CHARACTER VARYING(30),
    FullName CHARACTER VARYING(30),
    Adress CHARACTER VARYING(30),
    Age INTEGER
);